### ISSUE TITLE
Running in local server

### ISSUE THREAD

**Issue by yonkyunior** [jglovier/jglovier.github.io#65]
I would like to view your site with local server,
just running 'jekyll serve' give me an error

i had installed jekyll 3.0.0
and i just walk to jekyll just a few days, i'm just a noob right now.
```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

E:\jglovier.github.io-master>jekyll serve
Configuration file: E:/jglovier.github.io-master/_config.yml
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb
:30:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:30:in `block in require_gems'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:27:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:27:in `require_gems'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:19:in `conscientious_require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site
.rb:97:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site
.rb:49:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/build.rb:30:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/build.rb:30:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/bin/jekyll:17:i
n `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'

E:\jglovier.github.io-master>bundle exec serve
bundler: command not found: serve
Install missing gem executables with `bundle install`

E:\jglovier.github.io-master>

```

i dont find a clue about this,

**Comment by jglovier** [comment]
So you actually need to run `bundle exec jekyll serve` because of bundler. I'll update the readme to reflect that. Sorry for the trouble.
